### ISSUE TITLE
syntax issue in install_db file

### ISSUE THREAD

**Issue by bremanandjk** [PBSPro/pbspro#1020]
While running install_db for database creation, this script will preserve the existing password file.
There is a syntax issue while verifying the "upgrade" variable.

**Execution logs:**

[root@physics scripts]# /opt/pbs/libexec/install_db
/opt/pbs/libexec/install_db: line 223: [0: command not found
Creating the PBS Data Service...
Starting PBS Data Service..
Stopping PBS Data Service..
waiting for server to shut down.... done
server stopped

It's not harming in the creation of a database for vanilla install, it causes an issue while saving the password for an upgrade scenario.

**Comment by agrawalravi90** [comment]
PR: https://github.com/PBSPro/pbspro/pull/1019

**Comment by agrawalravi90** [comment]
I guess we can close this issue @bremanandjk ?

**Comment by bremanandjk** [comment]
yes, @agrawalravi90.  Thanks for merging this PR. 
I am closing this "issue" as completed.
