### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kguay** [PBSPro/pbspro#1073]
I am familiar with the PDF documentation for PBS Pro, but is there a website with the documentation that would be easier to search and view? If not, could I convert some or all of it to markdown in order to easily display on the web? I was reading the copyright notice on the user guide and am unclear whether that applies to the documentation or just the software.

Ideally, the Altair folks could compile the documentation into markdown or HTML and add it to a new GitHub repository and serve it using GitHub Pages.

**Comment by billnitzberg** [comment]
Thanks for the suggestion -- I'll pass it along to the Altair documentation team.

The PDF documentation has a different copyright/license than the Open Source project.  The PBS Pro Open Source project software is Open Source (AGPLv3), so free to use under the AGPLv3 license.  The PDF docs (at https://www.pbsworks.com/SupportGT.aspx?d=PBS-Professional,-Documentation) are commercially licensed, so not Open Source.

The best way to search the PDF docs is to search the "Big Book" (which includes all the guides, concatenated and indexed together) in one PDF doc.

**Comment by kguay** [comment]
Thanks for passing it along @billnitzberg. The "Big Book" seems helpful, although it is extremely slow to search through it. A website would be really nice.

Thanks again.

**Comment by janxkoci** [comment]
Hi, would you mind linking to the documentation somewhere more prominently? Neither the readme nor the website at openpbs.org have any link to any documentation, which is really weird. A user should not be forced to search an issue tracker, like me, to find this info.
