### ISSUE TITLE
support for DRMAA?

### ISSUE THREAD

**Issue by AntonioJBT** [PBSPro/pbspro#1259]
Hi,
This is just a question I can't find an answer to elsewhere, is there support for DRMAA for PBSPro (or plans for)?
There's a third party library:
http://apps.man.poznan.pl/trac/pbs-drmaa/wiki
but this no longer seems to work for us (I'm a PBSPro user) and unsure if it is being maintained.
Best wishes,
Antonio

**Comment by mike0042** [comment]
Hello @AntonioJBT,
I don't know the current state, but there was some work on this a few years back. You may find the following useful: https://github.com/PBSPro/DRMAAv2
Thanks,
Mike

**Comment by AntonioJBT** [comment]
Hi Mike,
Many thanks, I've moved this to [issue 26](https://github.com/PBSPro/DRMAAv2/issues/26) in that repository.
Best,
Antonio
