### ISSUE TITLE
pbsnodes shows state = initializing and down

### ISSUE THREAD

**Issue by thrubovc** [PBSPro/pbspro#1408]
I have a new pbs server + execution node setup. When I create node in qmgr, pbsnodes -a shows this:

[root@gdcrstoap702 pbs]# pbsnodes -a
gdcrstoap702
     Mom = <various>
     Port = 15002
     pbs_version = 18.1.2
     ntype = PBS
     state = <various>
     pcpus = <various>
     comment = node down: communication closed
     resv_enable = True
     sharing = <various>
     last_state_change_time = Thu Jan  1 01:00:00 1970
     last_used_time = Thu Jan  1 01:00:00 1970
     resources_available.arch = linux
     resources_available.host = gdcrstoap702
     resources_available.mem = 24777144kb
     resources_available.ncpus = 5
     resources_available.vnode = <various>
     resources_available.accelerator_memory = 0kb
     resources_available.hbmem = 0kb
     resources_available.naccelerators = 0
     resources_available.vmem = 0kb
     resources_available.department = <various>
     resources_assigned.mem = 0kb
     resources_assigned.ncpus = 0
     resources_assigned.accelerator_memory = 0kb
     resources_assigned.hbmem = 0kb
     resources_assigned.naccelerators = 0
     resources_assigned.vmem = 0kb

gdcrstoap011
     Mom = gdcrstoap011, gdcrstoap702
     Port = 15002
     pbs_version = 18.1.2
     ntype = PBS
     state = initializing
     pcpus = 2
     resources_available.arch = linux
     resources_available.host = gdcrstoap011
     resources_available.mem = 7999928kb
     resources_available.ncpus = 2
     resources_available.vnode = gdcrstoap011
     resources_assigned.accelerator_memory = 0kb
     resources_assigned.hbmem = 0kb
     resources_assigned.mem = 0kb
     resources_assigned.naccelerators = 0
     resources_assigned.ncpus = 0
     resources_assigned.vmem = 0kb
     resv_enable = True
     sharing = default_shared
     last_state_change_time = Wed Nov 20 09:17:43 2019

and after a while, the gdcrstoap011 node shows with state = down and the comment says "node down: communication closed"

my /etc/pbs.conf on server:
PBS_SERVER=gdcrstoap702
PBS_MOM_NODE_NAME=gdcrstoap011
PBS_START_SERVER=1
PBS_START_SCHED=1
PBS_START_COMM=1
PBS_START_MOM=1
PBS_EXEC=/opt/pbs
PBS_HOME=/var/spool/pbs
PBS_CORE_LIMIT=unlimited
PBS_SCP=/bin/scp

and on execution node:
PBS_SERVER=gdcrstoap702
PBS_START_MOM=1
PBS_EXEC=/opt/pbs
PBS_HOME=/var/spool/pbs
PBS_CORE_LIMIT=unlimited
PBS_SCP=/bin/scp
PBS_START_SERVER=0
PBS_START_SCHED=0
PBS_START_COMM=0

all ports and connectivity work, name resolution also works fine.
am I missing some piece of configuration?

**Comment by mike0042** [comment]
Are you certain that name resolution is working properly? The reason I ask is the "Mom =" lines in the pbsnodes output. The first is empty, and the second has two entries. Once you confirm name resolution is working, delete the existing nodes and create new ones by explicitly setting the Mom value. For example:
```
qmgr -c "delete node gdcrstoap702"
qmgr -c "create node gdcrstoap702 Mom=gdcrstoap702"
```

**Comment by thrubovc** [comment]
Thank you for the idea. however, I have discovered the reason behind my problem:
I forgot to mention that the execution node was running pbs v19 while the server v18, so I upgraded the server version to the same as on exec node. Then, my setup started working, even without specifying Mom explicitly.

**Comment by mike0042** [comment]
Glad to hear you have it working now! Closing the ticket.
