### ISSUE TITLE
qmgr configuration changes should be logged

### ISSUE THREAD

**Issue by datakid** [PBSPro/pbspro#1429]
I recently had the issue that we understood cpuset to be enabled. On inspection we discovered that it wasn't. We don't know who or how this was changed. 

It would be great if configuration changes in qmgr were logged somewhere.

[This issue opened on recommendation](http://community.pbspro.org/t/where-are-changes-in-qmgr-logged/1883/6)

**Comment by bhroam** [comment]
Attribute changes done through qmgr are logged in the server log.  You'll see the Type 11 request come in from the person running qmgr followed by the attribute that has changed.

**Comment by datakid** [comment]
Thanks
