### ISSUE TITLE
qmgr man pages namespace conflict with postfix's qmgr

### ISSUE THREAD

**Issue by datakid** [PBSPro/pbspro#1673]
Can I propose that the PBSPro man page for [qmgr](https://github.com/PBSPro/pbspro/blob/master/doc/man8/qmgr.8B) be re-named to pbs-qmgr to prevent the conflict with the [Postfix queue manager](http://www.postfix.org/qmgr.8.html)

**Comment by mike0042** [comment]
The qmgr online man pages should be in different sections. The qmgr(8B) man page covers the PBS qmgr command and the qmgr(8) man page covers the command for Postfix. Most current implementations of the man command will ask you which one you want if they find more than one. Also, PBS predates Postfix by a few years so I think Postfix should change (kidding, sort of).

That said, if others would like this as well we can certainly consider it.

**Comment by datakid** [comment]
Fair enough - I didn't realise that man 8B would give me what I needed, thanks. We are using Redhat 7.7 - I know it's soon to be EOL but I'd have imagined it was sufficiently modern. I guess since you've made it 8B it doesn't see a clash? Thanks
